// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models;

namespace _162120012_AliSARI_DuzceUniversitesi_WebSitesi.Migrations
{
    [DbContext(typeof(AndDB))]
    [Migration("20211213130016_DeleteDuyuruKategori")]
    partial class DeleteDuyuruKategori
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.AkademikCalismalar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FakulteID")
                        .HasColumnType("int");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("FakulteID");

                    b.ToTable("AkademikCalismalars");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.Bolum", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BolumAdi")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("nvarchar(90)");

                    b.Property<int>("FakulteID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FakulteID");

                    b.ToTable("Bolums");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.BolumGenelBilgileri", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aciklama10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aciklama11")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aciklama2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aciklama3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aciklama4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aciklama5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aciklama6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aciklama7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aciklama8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aciklama9")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BolognaSureciLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BolumID")
                        .HasColumnType("int");

                    b.Property<string>("Email1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email3")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("BolumID");

                    b.ToTable("BolumGenelBilgileris");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.BolumveProgramSayilari", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BolumveProgramSayilariKategoriID")
                        .HasColumnType("int");

                    b.Property<string>("Fakulte")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OgrenimTuru")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Sayisi")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("BolumveProgramSayilariKategoriID");

                    b.ToTable("BolumveProgramSayilaris");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.BolumveProgramSayilariKategori", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("BolumveProgramSayilariKategoris");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.ButceBilgileri", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ButceBilgileriKategoriID")
                        .HasColumnType("int");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ButceBilgileriKategoriID");

                    b.ToTable("ButceBilgileris");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.ButceBilgileriKategori", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("YilKategori")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("ID");

                    b.ToTable("ButceBilgileriKategoris");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.DersProgramlari", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DersProgramlariKategoriID")
                        .HasColumnType("int");

                    b.Property<int>("FakulteID")
                        .HasColumnType("int");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DersProgramlariKategoriID");

                    b.HasIndex("FakulteID");

                    b.ToTable("DersProgramlaris");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.DersProgramlariKategori", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ID");

                    b.ToTable("DersProgramlariKategoris");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.Dukkan", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Baslık")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("nvarchar(90)");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Renkler")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResimUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Dukkans");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.Duyurular", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aciklama2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aciklama3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aciklama4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aciklama5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aciklama6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DuyuruKategori")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("nvarchar(90)");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResimUrl1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResimUrl2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResimUrl3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResimUrl4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResimUrl5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResimUrl6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResimUrl7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResimUrl8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Duyurulars");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.Enstitu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EnstituAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Enstitus");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.Fakulte", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FakulteAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Fakultes");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.FaliyetRaporu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EnstituID")
                        .HasColumnType("int");

                    b.Property<int?>("FakulteID")
                        .HasColumnType("int");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("EnstituID");

                    b.HasIndex("FakulteID");

                    b.ToTable("FaliyetRaporus");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.FormlarOgr", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnsitituicinYuksekLisansDoktara")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EnstituID")
                        .HasColumnType("int");

                    b.Property<int?>("FakulteID")
                        .HasColumnType("int");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("EnstituID");

                    b.HasIndex("FakulteID");

                    b.ToTable("FormlarOgrs");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.GenelBilgiler", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aciklama2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aciklama3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aciklama4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aciklama5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EkAciklama1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EkAciklama10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EkAciklama11")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EkAciklama12")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EkAciklama2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EkAciklama3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EkAciklama4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EkAciklama5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EkAciklama6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EkAciklama7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EkAciklama8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EkAciklama9")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EkBaslik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EnstituID")
                        .HasColumnType("int");

                    b.Property<int?>("FakulteID")
                        .HasColumnType("int");

                    b.Property<string>("Misyonumuz")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResimUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vizyonumuz")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("EnstituID");

                    b.HasIndex("FakulteID");

                    b.ToTable("GenelBilgilers");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.GorevTanimlari", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EnstituID")
                        .HasColumnType("int");

                    b.Property<int?>("FakulteID")
                        .HasColumnType("int");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("EnstituID");

                    b.HasIndex("FakulteID");

                    b.ToTable("GorevTanimlaris");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.HizmetStandartlariveEnvanteri", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FakulteID")
                        .HasColumnType("int");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("FakulteID");

                    b.ToTable("HizmetStandartlariveEnvanteris");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.IcDegerlendirmeRaporu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FakulteID")
                        .HasColumnType("int");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("FakulteID");

                    b.ToTable("IcDegerlendirmeRaporus");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.IsAkisSemalari", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Departman")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EnstituID")
                        .HasColumnType("int");

                    b.Property<int?>("FakulteID")
                        .HasColumnType("int");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("EnstituID");

                    b.HasIndex("FakulteID");

                    b.ToTable("ısAkisSemalaris");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.Isbirlikleri", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProtokolImzalananFirmalar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Isbirlikleris");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.Kullanici", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("TCKimlikNumarasi")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("ID");

                    b.ToTable("Kullanicis");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.KurullarVeKomisyonlar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EnstituID")
                        .HasColumnType("int");

                    b.Property<int?>("FakulteID")
                        .HasColumnType("int");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("EnstituID");

                    b.HasIndex("FakulteID");

                    b.ToTable("KurullarVeKomisyonlars");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.KurumIcDegerlendirmeRaporlari", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EnstituID")
                        .HasColumnType("int");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YılAyrintilari")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("EnstituID");

                    b.ToTable("KurumIcDegerlendirmeRaporlaris");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.Mevzuat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EnstituID")
                        .HasColumnType("int");

                    b.Property<int?>("FakulteID")
                        .HasColumnType("int");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("EnstituID");

                    b.HasIndex("FakulteID");

                    b.ToTable("Mevzuats");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.OgrenciDanismanligi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BolumAdi")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("DanismanAd")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DanismanSoyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DanismanUnvan")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("FakulteID")
                        .HasColumnType("int");

                    b.Property<int>("Sinif")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("FakulteID");

                    b.ToTable("OgrenciDanismanligis");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.OgrenciSayilari", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AkademikBirim")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ErkekSayisi")
                        .HasColumnType("int");

                    b.Property<int>("KadinSayisi")
                        .HasColumnType("int");

                    b.Property<string>("OgrenimDuzeyi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("OgrenciSayilaris");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.OrganizasyonSemasi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EnstituID")
                        .HasColumnType("int");

                    b.Property<int?>("FakulteID")
                        .HasColumnType("int");

                    b.Property<string>("ResimUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("EnstituID");

                    b.HasIndex("FakulteID");

                    b.ToTable("OrganizasyonSemasis");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.Personel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aciklama2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aciklama3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aciklama4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aciklama5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("BolumID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("EnstituID")
                        .HasColumnType("int");

                    b.Property<int?>("FakulteID")
                        .HasColumnType("int");

                    b.Property<string>("FotografUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonelKategoriID")
                        .HasColumnType("int");

                    b.Property<string>("PersonelLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TCKimlikNumarasi")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Unvan")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Yayinlar1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yayinlar10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yayinlar11")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yayinlar12")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yayinlar2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yayinlar3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yayinlar4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yayinlar5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yayinlar6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yayinlar7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yayinlar8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yayinlar9")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("BolumID");

                    b.HasIndex("EnstituID");

                    b.HasIndex("FakulteID");

                    b.HasIndex("PersonelKategoriID");

                    b.ToTable("Personels");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.PersonelKategori", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("PersonelKategoris");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.PersonelSayilari", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HizmetYeri")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("PersonelSayilariKategoriID")
                        .HasColumnType("int");

                    b.Property<int>("Sayi")
                        .HasColumnType("int");

                    b.Property<string>("Unvan")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("ID");

                    b.HasIndex("PersonelSayilariKategoriID");

                    b.ToTable("PersonelSayilaris");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.PersonelSayilariKategori", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("ID");

                    b.ToTable("PersonelSayilariKategoris");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.StratejikPlanRaporlari", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StratejikPlanRaporlariKategoriID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("StratejikPlanRaporlariKategoriID");

                    b.ToTable("StratejikPlanRaporlaris");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.StratejikPlanRaporlariKategori", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("ID");

                    b.ToTable("StratejikPlanRaporlariKategoris");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.UniversiteIzlemeveDgrRapor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Kriterler")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Say_Oran")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("UniversiteIzlemeveDgrRaporKategoriID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UniversiteIzlemeveDgrRaporKategoriID");

                    b.ToTable("UniversiteIzlemeveDgrRapors");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.UniversiteIzlemeveDgrRaporKategori", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("UniversiteIzlemeveDgrRaporKategoris");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.Yonetim", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aciklama2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aciklama3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aciklama4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aciklama5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<string>("BolumDali")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BolumGorevi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BolumID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("EnstituID")
                        .HasColumnType("int");

                    b.Property<int?>("FakulteID")
                        .HasColumnType("int");

                    b.Property<string>("FotografUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Unvan")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Yayinlar1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yayinlar10")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yayinlar11")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yayinlar12")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yayinlar2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yayinlar3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yayinlar4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yayinlar5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yayinlar6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yayinlar7")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yayinlar8")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yayinlar9")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YonetimKategoriID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("BolumID");

                    b.HasIndex("EnstituID");

                    b.HasIndex("FakulteID");

                    b.HasIndex("YonetimKategoriID");

                    b.ToTable("Yonetims");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.YonetimKategori", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Gorevi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("YonetimKategoris");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.YonetmelikVeYonergeler", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<int>("YonetmelikVeYonergelerKategoriID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("YonetmelikVeYonergelerKategoriID");

                    b.ToTable("YonetmelikVeYonergelers");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.YonetmelikVeYonergelerKategori", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("ID");

                    b.ToTable("YonetmelikVeYonergelerKategoris");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.AkademikCalismalar", b =>
                {
                    b.HasOne("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.Fakulte", "Fakulte")
                        .WithMany()
                        .HasForeignKey("FakulteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fakulte");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.Bolum", b =>
                {
                    b.HasOne("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.Fakulte", "Fakulte")
                        .WithMany()
                        .HasForeignKey("FakulteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fakulte");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.BolumGenelBilgileri", b =>
                {
                    b.HasOne("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.Bolum", "Bolum")
                        .WithMany()
                        .HasForeignKey("BolumID");

                    b.Navigation("Bolum");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.BolumveProgramSayilari", b =>
                {
                    b.HasOne("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.BolumveProgramSayilariKategori", "BolumveProgramSayilariKategori")
                        .WithMany()
                        .HasForeignKey("BolumveProgramSayilariKategoriID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BolumveProgramSayilariKategori");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.ButceBilgileri", b =>
                {
                    b.HasOne("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.ButceBilgileriKategori", "ButceBilgileriKategori")
                        .WithMany()
                        .HasForeignKey("ButceBilgileriKategoriID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ButceBilgileriKategori");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.DersProgramlari", b =>
                {
                    b.HasOne("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.DersProgramlariKategori", "DersProgramlariKategori")
                        .WithMany()
                        .HasForeignKey("DersProgramlariKategoriID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.Fakulte", "Fakulte")
                        .WithMany()
                        .HasForeignKey("FakulteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DersProgramlariKategori");

                    b.Navigation("Fakulte");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.FaliyetRaporu", b =>
                {
                    b.HasOne("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.Enstitu", "Enstitu")
                        .WithMany()
                        .HasForeignKey("EnstituID");

                    b.HasOne("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.Fakulte", "Fakulte")
                        .WithMany()
                        .HasForeignKey("FakulteID");

                    b.Navigation("Enstitu");

                    b.Navigation("Fakulte");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.FormlarOgr", b =>
                {
                    b.HasOne("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.Enstitu", "Enstitu")
                        .WithMany()
                        .HasForeignKey("EnstituID");

                    b.HasOne("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.Fakulte", "Fakulte")
                        .WithMany()
                        .HasForeignKey("FakulteID");

                    b.Navigation("Enstitu");

                    b.Navigation("Fakulte");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.GenelBilgiler", b =>
                {
                    b.HasOne("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.Enstitu", "Enstitu")
                        .WithMany()
                        .HasForeignKey("EnstituID");

                    b.HasOne("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.Fakulte", "Fakulte")
                        .WithMany()
                        .HasForeignKey("FakulteID");

                    b.Navigation("Enstitu");

                    b.Navigation("Fakulte");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.GorevTanimlari", b =>
                {
                    b.HasOne("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.Enstitu", "Enstitu")
                        .WithMany()
                        .HasForeignKey("EnstituID");

                    b.HasOne("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.Fakulte", "Fakulte")
                        .WithMany()
                        .HasForeignKey("FakulteID");

                    b.Navigation("Enstitu");

                    b.Navigation("Fakulte");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.HizmetStandartlariveEnvanteri", b =>
                {
                    b.HasOne("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.Fakulte", "Fakulte")
                        .WithMany()
                        .HasForeignKey("FakulteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fakulte");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.IcDegerlendirmeRaporu", b =>
                {
                    b.HasOne("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.Fakulte", "Fakulte")
                        .WithMany()
                        .HasForeignKey("FakulteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fakulte");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.IsAkisSemalari", b =>
                {
                    b.HasOne("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.Enstitu", "Enstitu")
                        .WithMany()
                        .HasForeignKey("EnstituID");

                    b.HasOne("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.Fakulte", "Fakulte")
                        .WithMany()
                        .HasForeignKey("FakulteID");

                    b.Navigation("Enstitu");

                    b.Navigation("Fakulte");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.KurullarVeKomisyonlar", b =>
                {
                    b.HasOne("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.Enstitu", "Enstitu")
                        .WithMany()
                        .HasForeignKey("EnstituID");

                    b.HasOne("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.Fakulte", "Fakulte")
                        .WithMany()
                        .HasForeignKey("FakulteID");

                    b.Navigation("Enstitu");

                    b.Navigation("Fakulte");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.KurumIcDegerlendirmeRaporlari", b =>
                {
                    b.HasOne("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.Enstitu", "Enstitu")
                        .WithMany()
                        .HasForeignKey("EnstituID");

                    b.Navigation("Enstitu");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.Mevzuat", b =>
                {
                    b.HasOne("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.Enstitu", "Enstitu")
                        .WithMany()
                        .HasForeignKey("EnstituID");

                    b.HasOne("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.Fakulte", "Fakulte")
                        .WithMany()
                        .HasForeignKey("FakulteID");

                    b.Navigation("Enstitu");

                    b.Navigation("Fakulte");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.OgrenciDanismanligi", b =>
                {
                    b.HasOne("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.Fakulte", "Fakulte")
                        .WithMany()
                        .HasForeignKey("FakulteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fakulte");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.OrganizasyonSemasi", b =>
                {
                    b.HasOne("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.Enstitu", "Enstitu")
                        .WithMany()
                        .HasForeignKey("EnstituID");

                    b.HasOne("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.Fakulte", "Fakulte")
                        .WithMany()
                        .HasForeignKey("FakulteID");

                    b.Navigation("Enstitu");

                    b.Navigation("Fakulte");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.Personel", b =>
                {
                    b.HasOne("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.Bolum", "Bolum")
                        .WithMany()
                        .HasForeignKey("BolumID");

                    b.HasOne("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.Enstitu", "Enstitu")
                        .WithMany()
                        .HasForeignKey("EnstituID");

                    b.HasOne("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.Fakulte", "Fakulte")
                        .WithMany()
                        .HasForeignKey("FakulteID");

                    b.HasOne("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.PersonelKategori", "PersonelKategori")
                        .WithMany()
                        .HasForeignKey("PersonelKategoriID");

                    b.Navigation("Bolum");

                    b.Navigation("Enstitu");

                    b.Navigation("Fakulte");

                    b.Navigation("PersonelKategori");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.PersonelSayilari", b =>
                {
                    b.HasOne("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.PersonelSayilariKategori", "PersonelSayilariKategori")
                        .WithMany()
                        .HasForeignKey("PersonelSayilariKategoriID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonelSayilariKategori");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.StratejikPlanRaporlari", b =>
                {
                    b.HasOne("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.StratejikPlanRaporlariKategori", "StratejikPlanRaporlariKategori")
                        .WithMany()
                        .HasForeignKey("StratejikPlanRaporlariKategoriID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StratejikPlanRaporlariKategori");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.UniversiteIzlemeveDgrRapor", b =>
                {
                    b.HasOne("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.UniversiteIzlemeveDgrRaporKategori", "UniversiteIzlemeveDgrRaporKategori")
                        .WithMany()
                        .HasForeignKey("UniversiteIzlemeveDgrRaporKategoriID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UniversiteIzlemeveDgrRaporKategori");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.Yonetim", b =>
                {
                    b.HasOne("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.Bolum", "Bolum")
                        .WithMany()
                        .HasForeignKey("BolumID");

                    b.HasOne("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.Enstitu", "Enstitu")
                        .WithMany()
                        .HasForeignKey("EnstituID");

                    b.HasOne("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.Fakulte", "Fakulte")
                        .WithMany()
                        .HasForeignKey("FakulteID");

                    b.HasOne("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.YonetimKategori", "YonetimKategori")
                        .WithMany()
                        .HasForeignKey("YonetimKategoriID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bolum");

                    b.Navigation("Enstitu");

                    b.Navigation("Fakulte");

                    b.Navigation("YonetimKategori");
                });

            modelBuilder.Entity("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.YonetmelikVeYonergeler", b =>
                {
                    b.HasOne("_162120012_AliSARI_DuzceUniversitesi_WebSitesi.Models.YonetmelikVeYonergelerKategori", "YonetmelikVeYonergelerKategori")
                        .WithMany()
                        .HasForeignKey("YonetmelikVeYonergelerKategoriID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("YonetmelikVeYonergelerKategori");
                });
#pragma warning restore 612, 618
        }
    }
}
